# Generated by Django 2.2.7 on 2019-12-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tootaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eesNimi', models.CharField(max_length=120)),
                ('perekonnaNimi', models.CharField(max_length=120)),
                ('asutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Asutus')),
            ],
        ),
    ]
