# Generated by Django 2.2.7 on 2019-12-12 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191212_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='TooajaTabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuupaev', models.DateField(default=datetime.date(2019, 12, 12))),
                ('tootunde', models.IntegerField(default=0)),
                ('tootaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tootaja')),
            ],
        ),
    ]
