# Generated by Django 2.2.7 on 2019-12-12 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tooajatabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooajatabel',
            name='kuupaev',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
